/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  IonicButton as IonicButton
} from './components/ionic-button/ionic-button';

declare global {
  interface HTMLIonicButtonElement extends IonicButton, HTMLElement {
  }
  var HTMLIonicButtonElement: {
    prototype: HTMLIonicButtonElement;
    new (): HTMLIonicButtonElement;
  };
  interface HTMLElementTagNameMap {
    "ionic-button": HTMLIonicButtonElement;
  }
  interface ElementTagNameMap {
    "ionic-button": HTMLIonicButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ionic-button": JSXElements.IonicButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface IonicButtonAttributes extends HTMLAttributes {
      
        color?: string,
        type?: string,
        disabled?: boolean
    }
  }
}


import {
  IonicNewsletterSignup as IonicNewsletterSignup
} from './components/ionic-newsletter-signup/ionic-newsletter-signup';

declare global {
  interface HTMLIonicNewsletterSignupElement extends IonicNewsletterSignup, HTMLElement {
  }
  var HTMLIonicNewsletterSignupElement: {
    prototype: HTMLIonicNewsletterSignupElement;
    new (): HTMLIonicNewsletterSignupElement;
  };
  interface HTMLElementTagNameMap {
    "ionic-newsletter-signup": HTMLIonicNewsletterSignupElement;
  }
  interface ElementTagNameMap {
    "ionic-newsletter-signup": HTMLIonicNewsletterSignupElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ionic-newsletter-signup": JSXElements.IonicNewsletterSignupAttributes;
    }
  }
  namespace JSXElements {
    export interface IonicNewsletterSignupAttributes extends HTMLAttributes {
      
    }
  }
}

